/**
 * Built-in exercise library.
 *
 * Stored as tuples rather than objects purely for density — ~230 entries as
 * full object literals would be several thousand lines of mostly punctuation.
 * `buildExerciseLibrary()` in ./index.ts expands these into real records.
 *
 * Tuple shape: [name, equipment, primaryMuscle, secondaryMuscles?, trackingType?]
 * `trackingType` defaults to 'weight_reps'.
 */

import type { Equipment, MuscleGroup, TrackingType } from '../types.ts';

export type ExerciseSeed = readonly [
  name: string,
  equipment: Equipment,
  primary: MuscleGroup,
  secondary?: readonly MuscleGroup[],
  tracking?: TrackingType,
];

export const EXERCISE_SEEDS: readonly ExerciseSeed[] = [
  // ---------------------------------------------------------------- Chest ---
  ['Bench Press (Barbell)', 'barbell', 'chest', ['triceps', 'shoulders']],
  ['Incline Bench Press (Barbell)', 'barbell', 'chest', ['shoulders', 'triceps']],
  ['Decline Bench Press (Barbell)', 'barbell', 'chest', ['triceps']],
  ['Close Grip Bench Press (Barbell)', 'barbell', 'triceps', ['chest', 'shoulders']],
  ['Bench Press (Dumbbell)', 'dumbbell', 'chest', ['triceps', 'shoulders']],
  ['Incline Bench Press (Dumbbell)', 'dumbbell', 'chest', ['shoulders', 'triceps']],
  ['Decline Bench Press (Dumbbell)', 'dumbbell', 'chest', ['triceps']],
  ['Chest Fly (Dumbbell)', 'dumbbell', 'chest', ['shoulders']],
  ['Incline Chest Fly (Dumbbell)', 'dumbbell', 'chest', ['shoulders']],
  ['Chest Fly (Cable)', 'cable', 'chest', ['shoulders']],
  ['Low Cable Crossover', 'cable', 'chest', ['shoulders']],
  ['High Cable Crossover', 'cable', 'chest', ['shoulders']],
  ['Chest Press (Machine)', 'machine', 'chest', ['triceps', 'shoulders']],
  ['Incline Chest Press (Machine)', 'machine', 'chest', ['shoulders', 'triceps']],
  ['Pec Deck (Machine)', 'machine', 'chest', []],
  ['Bench Press (Smith Machine)', 'smith_machine', 'chest', ['triceps', 'shoulders']],
  ['Incline Bench Press (Smith Machine)', 'smith_machine', 'chest', ['shoulders', 'triceps']],
  ['Push Up', 'bodyweight', 'chest', ['triceps', 'shoulders'], 'bodyweight_reps'],
  ['Incline Push Up', 'bodyweight', 'chest', ['triceps', 'shoulders'], 'bodyweight_reps'],
  ['Decline Push Up', 'bodyweight', 'chest', ['shoulders', 'triceps'], 'bodyweight_reps'],
  ['Wide Push Up', 'bodyweight', 'chest', ['shoulders'], 'bodyweight_reps'],
  ['Diamond Push Up', 'bodyweight', 'triceps', ['chest'], 'bodyweight_reps'],
  ['Chest Dip', 'bodyweight', 'chest', ['triceps', 'shoulders'], 'weighted_bodyweight'],
  ['Chest Dip (Assisted)', 'machine', 'chest', ['triceps'], 'assisted_bodyweight'],
  ['Landmine Press', 'barbell', 'chest', ['shoulders', 'triceps']],
  ['Svend Press', 'plate', 'chest', ['shoulders']],

  // ----------------------------------------------------------------- Back ---
  ['Deadlift (Barbell)', 'barbell', 'lower_back', ['glutes', 'hamstrings', 'traps', 'lats']],
  ['Sumo Deadlift (Barbell)', 'barbell', 'glutes', ['quads', 'lower_back', 'hamstrings']],
  ['Romanian Deadlift (Barbell)', 'barbell', 'hamstrings', ['glutes', 'lower_back']],
  ['Romanian Deadlift (Dumbbell)', 'dumbbell', 'hamstrings', ['glutes', 'lower_back']],
  ['Stiff Leg Deadlift (Barbell)', 'barbell', 'hamstrings', ['glutes', 'lower_back']],
  ['Deficit Deadlift (Barbell)', 'barbell', 'lower_back', ['glutes', 'hamstrings']],
  ['Rack Pull (Barbell)', 'barbell', 'traps', ['lower_back', 'glutes', 'lats']],
  ['Trap Bar Deadlift', 'barbell', 'glutes', ['quads', 'traps', 'lower_back']],
  ['Pull Up', 'bodyweight', 'lats', ['biceps', 'upper_back'], 'weighted_bodyweight'],
  ['Chin Up', 'bodyweight', 'lats', ['biceps'], 'weighted_bodyweight'],
  ['Neutral Grip Pull Up', 'bodyweight', 'lats', ['biceps', 'upper_back'], 'weighted_bodyweight'],
  ['Pull Up (Assisted)', 'machine', 'lats', ['biceps'], 'assisted_bodyweight'],
  ['Lat Pulldown (Cable)', 'cable', 'lats', ['biceps', 'upper_back']],
  ['Wide Grip Lat Pulldown (Cable)', 'cable', 'lats', ['upper_back', 'biceps']],
  ['Close Grip Lat Pulldown (Cable)', 'cable', 'lats', ['biceps']],
  ['Reverse Grip Lat Pulldown (Cable)', 'cable', 'lats', ['biceps']],
  ['Single Arm Lat Pulldown (Cable)', 'cable', 'lats', ['biceps']],
  ['Straight Arm Pulldown (Cable)', 'cable', 'lats', ['triceps']],
  ['Bent Over Row (Barbell)', 'barbell', 'upper_back', ['lats', 'biceps', 'lower_back']],
  ['Pendlay Row (Barbell)', 'barbell', 'upper_back', ['lats', 'biceps']],
  ['Yates Row (Barbell)', 'barbell', 'upper_back', ['lats', 'biceps']],
  ['T-Bar Row', 'barbell', 'upper_back', ['lats', 'biceps']],
  ['Bent Over Row (Dumbbell)', 'dumbbell', 'upper_back', ['lats', 'biceps']],
  ['Single Arm Row (Dumbbell)', 'dumbbell', 'lats', ['upper_back', 'biceps']],
  ['Chest Supported Row (Dumbbell)', 'dumbbell', 'upper_back', ['lats', 'biceps']],
  ['Seal Row (Barbell)', 'barbell', 'upper_back', ['lats', 'biceps']],
  ['Seated Row (Cable)', 'cable', 'upper_back', ['lats', 'biceps']],
  ['Single Arm Seated Row (Cable)', 'cable', 'upper_back', ['lats', 'biceps']],
  ['Wide Grip Seated Row (Cable)', 'cable', 'upper_back', ['lats', 'biceps']],
  ['Seated Row (Machine)', 'machine', 'upper_back', ['lats', 'biceps']],
  ['Chest Supported Row (Machine)', 'machine', 'upper_back', ['lats', 'biceps']],
  ['Inverted Row', 'bodyweight', 'upper_back', ['lats', 'biceps'], 'weighted_bodyweight'],
  ['Face Pull (Cable)', 'cable', 'shoulders', ['upper_back', 'traps']],
  ['Back Extension', 'bodyweight', 'lower_back', ['glutes', 'hamstrings'], 'weighted_bodyweight'],
  ['Back Extension (Machine)', 'machine', 'lower_back', ['glutes', 'hamstrings']],
  ['Reverse Hyperextension', 'machine', 'glutes', ['lower_back', 'hamstrings']],
  ['Good Morning (Barbell)', 'barbell', 'hamstrings', ['lower_back', 'glutes']],

  // ------------------------------------------------------------ Shoulders ---
  ['Overhead Press (Barbell)', 'barbell', 'shoulders', ['triceps', 'traps']],
  ['Seated Overhead Press (Barbell)', 'barbell', 'shoulders', ['triceps']],
  ['Push Press (Barbell)', 'barbell', 'shoulders', ['triceps', 'quads']],
  ['Behind The Neck Press (Barbell)', 'barbell', 'shoulders', ['triceps', 'traps']],
  ['Shoulder Press (Dumbbell)', 'dumbbell', 'shoulders', ['triceps']],
  ['Seated Shoulder Press (Dumbbell)', 'dumbbell', 'shoulders', ['triceps']],
  ['Arnold Press (Dumbbell)', 'dumbbell', 'shoulders', ['triceps']],
  ['Shoulder Press (Machine)', 'machine', 'shoulders', ['triceps']],
  ['Overhead Press (Smith Machine)', 'smith_machine', 'shoulders', ['triceps']],
  ['Lateral Raise (Dumbbell)', 'dumbbell', 'shoulders', []],
  ['Lateral Raise (Cable)', 'cable', 'shoulders', []],
  ['Lateral Raise (Machine)', 'machine', 'shoulders', []],
  ['Leaning Lateral Raise (Cable)', 'cable', 'shoulders', []],
  ['Front Raise (Dumbbell)', 'dumbbell', 'shoulders', []],
  ['Front Raise (Barbell)', 'barbell', 'shoulders', []],
  ['Front Raise (Cable)', 'cable', 'shoulders', []],
  ['Front Raise (Plate)', 'plate', 'shoulders', []],
  ['Rear Delt Fly (Dumbbell)', 'dumbbell', 'shoulders', ['upper_back']],
  ['Rear Delt Fly (Cable)', 'cable', 'shoulders', ['upper_back']],
  ['Reverse Pec Deck (Machine)', 'machine', 'shoulders', ['upper_back']],
  ['Upright Row (Barbell)', 'barbell', 'shoulders', ['traps', 'biceps']],
  ['Upright Row (Cable)', 'cable', 'shoulders', ['traps']],
  ['Cuban Press (Dumbbell)', 'dumbbell', 'shoulders', ['upper_back']],

  // ----------------------------------------------------------- Arms: Bis ---
  ['Bicep Curl (Barbell)', 'barbell', 'biceps', ['forearms']],
  ['Bicep Curl (EZ Bar)', 'barbell', 'biceps', ['forearms']],
  ['Wide Grip Curl (Barbell)', 'barbell', 'biceps', ['forearms']],
  ['Close Grip Curl (Barbell)', 'barbell', 'biceps', ['forearms']],
  ['Bicep Curl (Dumbbell)', 'dumbbell', 'biceps', ['forearms']],
  ['Alternating Bicep Curl (Dumbbell)', 'dumbbell', 'biceps', ['forearms']],
  ['Hammer Curl (Dumbbell)', 'dumbbell', 'biceps', ['forearms']],
  ['Incline Curl (Dumbbell)', 'dumbbell', 'biceps', ['forearms']],
  ['Concentration Curl (Dumbbell)', 'dumbbell', 'biceps', []],
  ['Spider Curl (Dumbbell)', 'dumbbell', 'biceps', []],
  ['Zottman Curl (Dumbbell)', 'dumbbell', 'biceps', ['forearms']],
  ['Preacher Curl (Barbell)', 'barbell', 'biceps', []],
  ['Preacher Curl (Dumbbell)', 'dumbbell', 'biceps', []],
  ['Preacher Curl (Machine)', 'machine', 'biceps', []],
  ['Bicep Curl (Cable)', 'cable', 'biceps', ['forearms']],
  ['Hammer Curl (Cable)', 'cable', 'biceps', ['forearms']],
  ['Bayesian Curl (Cable)', 'cable', 'biceps', []],
  ['Drag Curl (Barbell)', 'barbell', 'biceps', []],
  ['Reverse Curl (Barbell)', 'barbell', 'forearms', ['biceps']],

  // ---------------------------------------------------------- Arms: Tris ---
  ['Skull Crusher (EZ Bar)', 'barbell', 'triceps', []],
  ['Skull Crusher (Dumbbell)', 'dumbbell', 'triceps', []],
  ['JM Press (Barbell)', 'barbell', 'triceps', ['chest']],
  ['Overhead Extension (Dumbbell)', 'dumbbell', 'triceps', []],
  ['Overhead Extension (EZ Bar)', 'barbell', 'triceps', []],
  ['Overhead Extension (Cable)', 'cable', 'triceps', []],
  ['Tricep Pushdown (Cable)', 'cable', 'triceps', []],
  ['Rope Pushdown (Cable)', 'cable', 'triceps', []],
  ['V-Bar Pushdown (Cable)', 'cable', 'triceps', []],
  ['Reverse Grip Pushdown (Cable)', 'cable', 'triceps', []],
  ['Tricep Dip', 'bodyweight', 'triceps', ['chest', 'shoulders'], 'weighted_bodyweight'],
  ['Tricep Dip (Assisted)', 'machine', 'triceps', ['chest'], 'assisted_bodyweight'],
  ['Bench Dip', 'bodyweight', 'triceps', ['shoulders'], 'weighted_bodyweight'],
  ['Tricep Extension (Machine)', 'machine', 'triceps', []],
  ['Tricep Kickback (Dumbbell)', 'dumbbell', 'triceps', []],
  ['Tricep Kickback (Cable)', 'cable', 'triceps', []],

  // -------------------------------------------------------------- Forearms --
  ['Wrist Curl (Barbell)', 'barbell', 'forearms', []],
  ['Wrist Curl (Dumbbell)', 'dumbbell', 'forearms', []],
  ['Reverse Wrist Curl (Barbell)', 'barbell', 'forearms', []],
  ['Behind The Back Wrist Curl (Barbell)', 'barbell', 'forearms', []],
  ['Wrist Roller', 'other', 'forearms', []],
  ['Plate Pinch', 'plate', 'forearms', [], 'duration'],
  ["Farmer's Walk", 'dumbbell', 'forearms', ['traps', 'full_body'], 'weight_distance'],

  // ------------------------------------------------------------ Legs: Quads --
  ['Squat (Barbell)', 'barbell', 'quads', ['glutes', 'hamstrings', 'lower_back']],
  ['High Bar Squat (Barbell)', 'barbell', 'quads', ['glutes', 'hamstrings']],
  ['Low Bar Squat (Barbell)', 'barbell', 'quads', ['glutes', 'lower_back']],
  ['Front Squat (Barbell)', 'barbell', 'quads', ['glutes', 'abs']],
  ['Box Squat (Barbell)', 'barbell', 'quads', ['glutes', 'hamstrings']],
  ['Pause Squat (Barbell)', 'barbell', 'quads', ['glutes']],
  ['Zercher Squat (Barbell)', 'barbell', 'quads', ['glutes', 'abs']],
  ['Squat (Smith Machine)', 'smith_machine', 'quads', ['glutes']],
  ['Goblet Squat (Dumbbell)', 'dumbbell', 'quads', ['glutes']],
  ['Hack Squat (Machine)', 'machine', 'quads', ['glutes']],
  ['V-Squat (Machine)', 'machine', 'quads', ['glutes']],
  ['Belt Squat (Machine)', 'machine', 'quads', ['glutes']],
  ['Leg Press (Machine)', 'machine', 'quads', ['glutes', 'hamstrings']],
  ['Single Leg Press (Machine)', 'machine', 'quads', ['glutes']],
  ['Leg Extension (Machine)', 'machine', 'quads', []],
  ['Single Leg Extension (Machine)', 'machine', 'quads', []],
  ['Bulgarian Split Squat (Dumbbell)', 'dumbbell', 'quads', ['glutes', 'hamstrings']],
  ['Bulgarian Split Squat (Barbell)', 'barbell', 'quads', ['glutes']],
  ['Split Squat (Dumbbell)', 'dumbbell', 'quads', ['glutes']],
  ['Walking Lunge (Dumbbell)', 'dumbbell', 'quads', ['glutes', 'hamstrings']],
  ['Reverse Lunge (Dumbbell)', 'dumbbell', 'quads', ['glutes']],
  ['Forward Lunge (Barbell)', 'barbell', 'quads', ['glutes']],
  ['Step Up (Dumbbell)', 'dumbbell', 'quads', ['glutes']],
  ['Sissy Squat', 'bodyweight', 'quads', [], 'weighted_bodyweight'],
  ['Bodyweight Squat', 'bodyweight', 'quads', ['glutes'], 'bodyweight_reps'],
  ['Pistol Squat', 'bodyweight', 'quads', ['glutes'], 'weighted_bodyweight'],

  // ------------------------------------------------ Legs: Hamstrings/Glutes --
  ['Lying Leg Curl (Machine)', 'machine', 'hamstrings', ['calves']],
  ['Seated Leg Curl (Machine)', 'machine', 'hamstrings', []],
  ['Standing Leg Curl (Machine)', 'machine', 'hamstrings', []],
  ['Nordic Hamstring Curl', 'bodyweight', 'hamstrings', [], 'weighted_bodyweight'],
  ['Glute Ham Raise', 'bodyweight', 'hamstrings', ['glutes'], 'weighted_bodyweight'],
  ['Single Leg Romanian Deadlift (Dumbbell)', 'dumbbell', 'hamstrings', ['glutes']],
  ['Hip Thrust (Barbell)', 'barbell', 'glutes', ['hamstrings']],
  ['Hip Thrust (Machine)', 'machine', 'glutes', ['hamstrings']],
  ['Single Leg Hip Thrust', 'bodyweight', 'glutes', ['hamstrings'], 'weighted_bodyweight'],
  ['Glute Bridge (Barbell)', 'barbell', 'glutes', ['hamstrings']],
  ['Glute Kickback (Cable)', 'cable', 'glutes', ['hamstrings']],
  ['Glute Kickback (Machine)', 'machine', 'glutes', ['hamstrings']],
  ['Pull Through (Cable)', 'cable', 'glutes', ['hamstrings', 'lower_back']],
  ['Hip Abduction (Machine)', 'machine', 'abductors', ['glutes']],
  ['Hip Adduction (Machine)', 'machine', 'adductors', []],
  ['Hip Abduction (Cable)', 'cable', 'abductors', ['glutes']],
  ['Copenhagen Plank', 'bodyweight', 'adductors', ['abs'], 'duration'],

  // ----------------------------------------------------------- Legs: Calves --
  ['Standing Calf Raise (Machine)', 'machine', 'calves', []],
  ['Seated Calf Raise (Machine)', 'machine', 'calves', []],
  ['Calf Raise (Barbell)', 'barbell', 'calves', []],
  ['Calf Raise (Dumbbell)', 'dumbbell', 'calves', []],
  ['Calf Press (Leg Press)', 'machine', 'calves', []],
  ['Calf Raise (Smith Machine)', 'smith_machine', 'calves', []],
  ['Donkey Calf Raise', 'machine', 'calves', []],
  ['Single Leg Calf Raise', 'bodyweight', 'calves', [], 'weighted_bodyweight'],

  // -------------------------------------------------------------- Traps/Neck --
  ['Shrug (Barbell)', 'barbell', 'traps', ['forearms']],
  ['Shrug (Dumbbell)', 'dumbbell', 'traps', ['forearms']],
  ['Shrug (Cable)', 'cable', 'traps', []],
  ['Shrug (Machine)', 'machine', 'traps', []],
  ['Shrug (Smith Machine)', 'smith_machine', 'traps', []],
  ['Neck Curl', 'other', 'neck', [], 'weighted_bodyweight'],
  ['Neck Extension', 'other', 'neck', [], 'weighted_bodyweight'],

  // ------------------------------------------------------------------ Core --
  ['Crunch', 'bodyweight', 'abs', [], 'bodyweight_reps'],
  ['Crunch (Cable)', 'cable', 'abs', []],
  ['Crunch (Machine)', 'machine', 'abs', []],
  ['Decline Crunch', 'bodyweight', 'abs', [], 'weighted_bodyweight'],
  ['Sit Up', 'bodyweight', 'abs', ['quads'], 'weighted_bodyweight'],
  ['Hanging Leg Raise', 'bodyweight', 'abs', ['forearms'], 'weighted_bodyweight'],
  ['Hanging Knee Raise', 'bodyweight', 'abs', ['forearms'], 'weighted_bodyweight'],
  ['Captains Chair Leg Raise', 'bodyweight', 'abs', [], 'weighted_bodyweight'],
  ['Lying Leg Raise', 'bodyweight', 'abs', [], 'bodyweight_reps'],
  ['Toes To Bar', 'bodyweight', 'abs', ['lats'], 'bodyweight_reps'],
  ['Plank', 'bodyweight', 'abs', ['obliques'], 'duration'],
  ['Side Plank', 'bodyweight', 'obliques', ['abs'], 'duration'],
  ['Hollow Body Hold', 'bodyweight', 'abs', [], 'duration'],
  ['Dead Bug', 'bodyweight', 'abs', [], 'bodyweight_reps'],
  ['Bicycle Crunch', 'bodyweight', 'obliques', ['abs'], 'bodyweight_reps'],
  ['Russian Twist', 'plate', 'obliques', ['abs']],
  ['Woodchopper (Cable)', 'cable', 'obliques', ['abs']],
  ['Pallof Press (Cable)', 'cable', 'obliques', ['abs']],
  ['Ab Wheel Rollout', 'other', 'abs', ['lats'], 'bodyweight_reps'],
  ['Mountain Climber', 'bodyweight', 'abs', ['shoulders'], 'bodyweight_reps'],
  ['V-Up', 'bodyweight', 'abs', [], 'bodyweight_reps'],
  ['Dragon Flag', 'bodyweight', 'abs', ['lower_back'], 'bodyweight_reps'],

  // ------------------------------------------------------- Olympic / Power --
  ['Clean and Jerk (Barbell)', 'barbell', 'full_body', ['quads', 'shoulders', 'traps']],
  ['Power Clean (Barbell)', 'barbell', 'full_body', ['quads', 'traps', 'glutes']],
  ['Hang Clean (Barbell)', 'barbell', 'full_body', ['traps', 'quads']],
  ['Snatch (Barbell)', 'barbell', 'full_body', ['shoulders', 'quads', 'traps']],
  ['Power Snatch (Barbell)', 'barbell', 'full_body', ['shoulders', 'traps']],
  ['Clean Pull (Barbell)', 'barbell', 'traps', ['glutes', 'hamstrings']],
  ['Snatch Pull (Barbell)', 'barbell', 'traps', ['glutes', 'hamstrings']],
  ['Push Jerk (Barbell)', 'barbell', 'shoulders', ['triceps', 'quads']],
  ['Split Jerk (Barbell)', 'barbell', 'shoulders', ['triceps', 'quads']],
  ['Thruster (Barbell)', 'barbell', 'full_body', ['quads', 'shoulders']],
  ['Kettlebell Swing', 'kettlebell', 'glutes', ['hamstrings', 'lower_back']],
  ['Turkish Get Up', 'kettlebell', 'full_body', ['shoulders', 'abs']],
  ['Burpee', 'bodyweight', 'full_body', ['chest', 'quads'], 'bodyweight_reps'],
  ['Box Jump', 'bodyweight', 'quads', ['glutes', 'calves'], 'bodyweight_reps'],
  ['Medicine Ball Slam', 'medicine_ball', 'full_body', ['abs', 'shoulders']],
  ['Battle Ropes', 'other', 'full_body', ['shoulders', 'abs'], 'duration'],
  ['Sled Push', 'other', 'quads', ['glutes', 'calves'], 'weight_distance'],
  ['Sled Pull', 'other', 'hamstrings', ['upper_back', 'glutes'], 'weight_distance'],

  // ---------------------------------------------------------------- Cardio --
  ['Running', 'bodyweight', 'cardio', ['quads', 'calves'], 'distance_duration'],
  ['Treadmill', 'cardio_machine', 'cardio', ['quads', 'calves'], 'distance_duration'],
  ['Incline Walk (Treadmill)', 'cardio_machine', 'cardio', ['glutes', 'calves'], 'distance_duration'],
  ['Walking', 'bodyweight', 'cardio', ['calves'], 'distance_duration'],
  ['Hiking', 'bodyweight', 'cardio', ['quads', 'glutes'], 'distance_duration'],
  ['Cycling', 'bodyweight', 'cardio', ['quads', 'calves'], 'distance_duration'],
  ['Stationary Bike', 'cardio_machine', 'cardio', ['quads'], 'distance_duration'],
  ['Assault Bike', 'cardio_machine', 'cardio', ['full_body'], 'distance_duration'],
  ['Elliptical', 'cardio_machine', 'cardio', ['quads', 'glutes'], 'distance_duration'],
  ['Rowing Machine', 'cardio_machine', 'cardio', ['upper_back', 'quads'], 'distance_duration'],
  ['Stair Master', 'cardio_machine', 'cardio', ['glutes', 'quads'], 'distance_duration'],
  ['Swimming', 'bodyweight', 'cardio', ['full_body'], 'distance_duration'],
  ['Jump Rope', 'other', 'cardio', ['calves'], 'duration'],
  ['Ski Erg', 'cardio_machine', 'cardio', ['lats', 'abs'], 'distance_duration'],

  // ------------------------------------------------------------ Stretching --
  ['Foam Rolling', 'other', 'full_body', [], 'duration'],
  ['Stretching', 'bodyweight', 'full_body', [], 'duration'],
  ['Yoga', 'bodyweight', 'full_body', [], 'duration'],
];
